 version: 2
 
 defaults: &defaults
 
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.18.0
    
 jobs:
   build:
     docker:
       - image: cimg/node:18.18.0
     steps:
       - checkout
       - run: pnpm i
       - run: pnpm start
       - run: pnpm lint
       - run: pnpm test
       - run: echo "Build Successful"
