 version: 2
 
 defaults: &defaults
 
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.18.0
    
 jobs:
   build:
     docker:
       - image: cimg/node:18.18.0
     steps:
       - checkout
       - run: yarn
       - run: yarn start
       - run: yarn lint
       - run: yarn test
       - run: echo "Build Successful"
