 version: 2
 
 defaults: &defaults
 
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.13.0
    
 jobs:
   build:
     docker:
       - image: circleci/node:12.13.0
     steps:
       - checkout
       - run: yarn install
       - run: node ./src/yayfetch.js
       - run: echo "Build Successful"
